############################################################
@local = https://localhost:6999
@deploy = https://

############################################################
### local test requests
POST {{local}}/getStatus
content-type: application/json

{
    "token": "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe"
}

###
POST {{local}}/cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe
content-type: application/json

{
    "token": "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe"
}

############################################################
### deployment requests
POST {{deploy}}/getStatus
content-type: application/json

{
}

###
POST {{deploy}}/deadbeefdeadbeefdeadbeefdeadbeef
content-type: application/json

{
}
