############################################################
@local = https://localhost:6999
@deploy = https://tst-lenny.weblenny.at

############################################################
### local test requests
POST {{local}}/getStatus
content-type: application/json

{
    "token": "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe"
}

###
POST {{local}}/cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe
content-type: application/json

{
    "token": "cafebabecafebabecafebabecafebabecafebabecafebabecafebabecafebabe",
    "action": "buy"
}

############################################################
### deployment requests
POST {{deploy}}/getStatus
content-type: application/json

{
}

###
POST {{deploy}}/e1tf5f17u2872v4c41y3d4g32kbdo9pd
content-type: application/json

{
    "token": ""
}
